[package]
name = "quokka"
version = "0.1.0"
edition = "2021"

[dependencies]
volatile-register = "0.2.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]

pl011 = []                        # Enables PL011 Support
system_console_pl011 = ["pl011"]  # Enables the PL011 as the system console

default = ["system_console_pl011"]
